// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: media.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (id, url, length_, mimetype)
VALUES ($1, $2, $3, $4)
RETURNING id, url, length_, mimetype
`

type CreateMediaParams struct {
	ID       uuid.UUID `json:"id"`
	Url      string    `json:"url"`
	Length   int32     `json:"length_"`
	Mimetype string    `json:"mimetype"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRowContext(ctx, createMedia,
		arg.ID,
		arg.Url,
		arg.Length,
		arg.Mimetype,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Length,
		&i.Mimetype,
	)
	return i, err
}
