services:
  rss-aggre:
    image: "rss-aggre:latest"
    depends_on:
      - db
    restart: always
    ports:
      - "443:443"
    environment:
      DATABASE_URL: "user=rss-aggre host=db port=5432 sslmode=disable"

      # added specifically for docker images
      DATABASE_PASSWORD_FILE: "/run/secrets/db_password"
    networks:
      - rss-aggre-network
    secrets:
      - db_password

  db:
    image: "postgres:15.4-alpine3.18"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: rss-aggre
      PG_DATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db_password
    networks:
      - rss-aggre-network

secrets:
  db_password:
    file: ./db_password.txt

networks:
  rss-aggre-network:

volumes:
  db_data:
    external:
      name: ${DATABASE_VOLUME}
